### ISSUE TITLE
Search function's category selection should only display categories that contain a nonzero amount of visible problems

### ISSUE THREAD

**Issue by zecookiez** [zecookiez/CBOJ#10]
This is very apparent when there are a lot of categories that aren't visible to most people (ICS classrooms).

**Comment by plasmatic1** [comment]
zekookez

**Comment by Ninjaclasher** [comment]
Should problem types be given the same sort of treatment or only problem categories?

**Comment by zecookiez** [comment]
Just problem category should be good enough I think.
