### ISSUE TITLE
Results page doesn't show code output

### ISSUE THREAD

**Issue by phynxinferno** [zecookiez/CBOJ#35]
thanks

**Comment by zecookiez** [comment]
This is intended behaviour, unfortunately.

The author of the problem has a field `Output prefix length`, which determines the amount of output to display whenever a test case receives a non-AC verdict:
![image](https://user-images.githubusercontent.com/13069724/189386251-ecee4449-e28f-4282-b48d-6a69ea9a3bc1.png)

If there is a specific problem that you want to display the output, you will need to contact the author of the problem to modify it. However, this also introduces the issue of displaying secret test cases that the author may want to keep hidden.

**Comment by phynxinferno** [comment]
thanks for clarifying. sorry for the unecessary issue.

**Comment by zecookiez** [comment]
No worries! Happy to answer concerns and feedback.
