### ISSUE TITLE
Accepting organization join requests doesn't do anything

### ISSUE THREAD

**Issue by c9utch** [zecookiez/CBOJ#36]
Title

**Comment by zecookiez** [comment]
Please be more specific. If you're referring to editing join requests from the Admin Page, it will not work and there are no plans to fix that.

There is the manage request page from the organization section, which takes care of this: 
![image](https://user-images.githubusercontent.com/13069724/189514165-878ffbf4-5cb9-4400-a03f-4771a9af656b.png)
